In [1]:
import pandas as pd
df=pd.read_csv('/content/drive/MyDrive/Sentiment Analysis Data/train.csv',engine='python', error_bad_lines=False)
df.head()

Skipping line 13535: field larger than field limit (131072)
Skipping line 15613: unexpected end of data
Skipping line 13541: Expected 5 fields in line 13541, saw 6


id  ... label
0  0  ...   1.0
1  1  ...   0.0
2  2  ...   1.0
3  3  ...   1.0
4  4  ...   1.0

[5 rows x 5 columns]

In [3]:
df=df.dropna()

In [4]:
## Get the Independent Features

X=df.drop('label',axis=1)
## Get the Dependent features
y=df['label']

In [5]:
import tensorflow as tf

In [6]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Bidirectional
from tensorflow.keras.layers import Dropout

In [7]:
voc_size=5000

In [9]:
messages=X.copy()
messages['title'][1]
messages.reset_index(inplace=True)
import nltk
import re
from nltk.corpus import stopwords

In [11]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [12]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    print(i)
    review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

Streaming output truncated to the last 5000 lines.
8703
8704
8705
8706
8707
8708
8709
8710
8711
8712
8713
8714
8715
8716
8717
8718
8719
8720
8721
8722
8723
8724
8725
8726
8727
8728
8729
8730
8731
8732
8733
8734
8735
8736
8737
8738
8739
8740
8741
8742
8743
8744
8745
8746
8747
8748
8749
8750
8751
8752
8753
8754
8755
8756
8757
8758
8759
8760
8761
8762
8763
8764
8765
8766
8767
8768
8769
8770
8771
8772
8773
8774
8775
8776
8777
8778
8779
8780
8781
8782
8783
8784
8785
8786
8787
8788
8789
8790
8791
8792
8793
8794
8795
8796
8797
8798
8799
8800
8801
8802
8803
8804
8805
8806
8807
8808
8809
8810
8811
8812
8813
8814
8815
8816
8817
8818
8819
8820
8821
8822
8823
8824
8825
8826
8827
8828
8829
8830
8831
8832
8833
8834
8835
8836
8837
8838
8839
8840
8841
8842
8843
8844
8845
8846
8847
8848
8849
8850
8851
8852
8853
8854
8855
8856
8857
8858
8859
8860
8861
8862
8863
8864
8865
8866
8867
8868
8869
8870
8871
8872
8873
8874
8875
8876
8877
8878
8879
8880
8881
8882
8883
8884
8885
8886
8887
8888
8889
8890
8891
8892

In [13]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [14]:
onehot_repr=[one_hot(words,voc_size)for words in corpus] 
onehot_repr

[[1515, 498, 2225, 2499, 734, 3116, 4030, 1122, 4273, 4386],
 [3920, 4794, 4756, 1027, 712, 761, 2949],
 [2845, 2525, 2555, 1550],
 [3106, 1374, 3467, 4718, 3361, 4742],
 [3965, 712, 87, 3722, 1961, 709, 712, 2592, 639, 3821],
 [2091,
  1288,
  3234,
  2398,
  2681,
  2069,
  317,
  2807,
  1597,
  455,
  2249,
  4174,
  1460,
  3251,
  2949],
 [3459, 160, 2706, 4763, 1697, 1113, 1048, 4585, 2501, 3046, 2736],
 [4036, 655, 4684, 2952, 4742, 2986, 2069, 4998, 2501, 3046, 2736],
 [108, 1426, 1719, 2076, 2057, 3025, 2622, 678, 2069, 4921],
 [1260, 1770, 4606, 3519, 1761, 4030, 1457, 397],
 [2970, 2354, 1644, 2171, 1060, 1336, 2169, 2165, 895, 1036, 2193],
 [4718, 4418, 734, 3025, 2069, 4742],
 [2702, 316, 1013, 3883, 3185, 4559, 3509, 4933, 2852],
 [561, 4680, 4820, 2365, 4274, 2857, 1565, 2501, 3046, 2736],
 [3643, 1331, 449, 2619, 700, 2501, 3046, 2736],
 [2062, 352, 1054, 4232, 2289, 1526, 1453, 2491, 4442, 794],
 [4521, 1754, 4794],
 [204, 24, 28, 508, 2069, 2958, 581, 2949],
 [364, 1

In [16]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ... 1122 4273 4386]
 [   0    0    0 ...  712  761 2949]
 [   0    0    0 ... 2525 2555 1550]
 ...
 [   0    0    0 ... 2501 3046 2736]
 [   0    0    0 ... 2501 3046 2736]
 [   0    0    0 ... 2102 1374  131]]


In [17]:
## Creating model
embedding_vector_features=40
model1=Sequential()
model1.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model1.add(Bidirectional(LSTM(100)))
model1.add(Dropout(0.3))
model1.add(Dense(1,activation='sigmoid'))
model1.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model1.summary())

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 20, 40)            200000    
                                                                 
 bidirectional (Bidirectiona  (None, 200)              112800    
 l)                                                              
                                                                 
 dropout (Dropout)           (None, 200)               0         
                                                                 
 dense (Dense)               (None, 1)                 201       
                                                                 
Total params: 313,001
Trainable params: 313,001
Non-trainable params: 0
_________________________________________________________________
None


In [18]:
len(embedded_docs),y.shape

(13703, (13703,))

In [19]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [20]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

In [21]:
### Finally Training
model1.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
144/144 [==============================] - 12s 29ms/step - loss: 0.3423 - accuracy: 0.8398 - val_loss: 0.2030 - val_accuracy: 0.9164
Epoch 2/10
144/144 [==============================] - 3s 21ms/step - loss: 0.1370 - accuracy: 0.9500 - val_loss: 0.2106 - val_accuracy: 0.9146
Epoch 3/10
144/144 [==============================] - 3s 21ms/step - loss: 0.0896 - accuracy: 0.9696 - val_loss: 0.2526 - val_accuracy: 0.9065
Epoch 4/10
144/144 [==============================] - 3s 20ms/step - loss: 0.0560 - accuracy: 0.9817 - val_loss: 0.3149 - val_accuracy: 0.9080
Epoch 5/10
144/144 [==============================] - 3s 22ms/step - loss: 0.0359 - accuracy: 0.9882 - val_loss: 0.4014 - val_accuracy: 0.9029
Epoch 6/10
144/144 [==============================] - 3s 20ms/step - loss: 0.0219 - accuracy: 0.9931 - val_loss: 0.4510 - val_accuracy: 0.8992
Epoch 7/10
144/144 [==============================] - 3s 20ms/step - loss: 0.0135 - accuracy: 0.9961 - val_loss: 0.5777 - val_accuracy: 0.898

In [28]:
y_pred1=model1.predict_classes(X_test)

AttributeError: ignored

In [26]:
from sklearn.metrics import confusion_matrix,classification_report

In [22]:
y_pred1=model1.predict_classes(X_test)

AttributeError: ignored

In [27]:
confusion_matrix(y_test,y_pred1)

NameError: ignored

In [24]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred1)

NameError: ignored

In [25]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred1))

NameError: ignored