In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
!pip install pandas

In [3]:
import pandas as pd

In [6]:
df=pd.read_csv('/content/drive/MyDrive/Sentiment Analysis Data/train.csv',engine='python', error_bad_lines=False)

Skipping line 13535: field larger than field limit (131072)
Skipping line 15613: unexpected end of data
Skipping line 13541: Expected 5 fields in line 13541, saw 6


In [7]:
df.head()

id  ... label
0  0  ...   1.0
1  1  ...   0.0
2  2  ...   1.0
3  3  ...   1.0
4  4  ...   1.0

[5 rows x 5 columns]

In [8]:
df.shape

(15609, 5)

In [ ]:
df1=pd.read_csv('fake_news_test.csv')

In [ ]:
df1.head()

id                                              title  \
0  20800  Specter of Trump Loosens Tongues, if Not Purse...   
1  20801  Russian warships ready to strike terrorists ne...   
2  20802  #NoDAPL: Native American Leaders Vow to Stay A...   
3  20803  Tim Tebow Will Attempt Another Comeback, This ...   
4  20804                    Keiser Report: Meme Wars (E995)   

                    author                                               text  
0         David Streitfeld  PALO ALTO, Calif.  —   After years of scorning...  
1                      NaN  Russian warships ready to strike terrorists ne...  
2            Common Dreams  Videos #NoDAPL: Native American Leaders Vow to...  
3            Daniel Victor  If at first you don’t succeed, try a different...  
4  Truth Broadcast Network  42 mins ago 1 Views 0 Comments 0 Likes 'For th...

In [9]:
df=df.dropna()

In [10]:
df.shape

(13703, 5)

In [11]:
## Get the Independent Features

X=df.drop('label',axis=1)

In [12]:
## Get the Dependent features
y=df['label']

In [13]:
X.shape

(13703, 4)

In [14]:
y.shape

(13703,)

In [15]:
import tensorflow as tf

In [16]:
print(tf.__version__)

2.7.0


In [17]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [18]:
### Vocabulary size
voc_size=5000

# One Hot Representation

In [19]:
messages=X.copy()

In [20]:
messages['title'][1]

'FLYNN: Hillary Clinton, Big Woman on Campus - Breitbart'

In [21]:
messages.reset_index(inplace=True)

In [22]:
import nltk
import re
from nltk.corpus import stopwords

In [23]:
#!pip install nltk

In [24]:
#!pip install re

In [27]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [28]:
### Dataset Preprocessing
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    print(i)
    review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

Streaming output truncated to the last 5000 lines.
8703
8704
8705
8706
8707
8708
8709
8710
8711
8712
8713
8714
8715
8716
8717
8718
8719
8720
8721
8722
8723
8724
8725
8726
8727
8728
8729
8730
8731
8732
8733
8734
8735
8736
8737
8738
8739
8740
8741
8742
8743
8744
8745
8746
8747
8748
8749
8750
8751
8752
8753
8754
8755
8756
8757
8758
8759
8760
8761
8762
8763
8764
8765
8766
8767
8768
8769
8770
8771
8772
8773
8774
8775
8776
8777
8778
8779
8780
8781
8782
8783
8784
8785
8786
8787
8788
8789
8790
8791
8792
8793
8794
8795
8796
8797
8798
8799
8800
8801
8802
8803
8804
8805
8806
8807
8808
8809
8810
8811
8812
8813
8814
8815
8816
8817
8818
8819
8820
8821
8822
8823
8824
8825
8826
8827
8828
8829
8830
8831
8832
8833
8834
8835
8836
8837
8838
8839
8840
8841
8842
8843
8844
8845
8846
8847
8848
8849
8850
8851
8852
8853
8854
8855
8856
8857
8858
8859
8860
8861
8862
8863
8864
8865
8866
8867
8868
8869
8870
8871
8872
8873
8874
8875
8876
8877
8878
8879
8880
8881
8882
8883
8884
8885
8886
8887
8888
8889
8890
8891
8892

In [29]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [30]:
onehot_repr=[one_hot(words,voc_size)for words in corpus] 
onehot_repr

[[1971, 1692, 1392, 4940, 4377, 1106, 1260, 4786, 2539, 4738],
 [4130, 2706, 4369, 3069, 3878, 4114, 2420],
 [1296, 304, 3803, 1562],
 [1308, 37, 28, 881, 4048, 4330],
 [2057, 3878, 2923, 3111, 1032, 4259, 3878, 4626, 1275, 1342],
 [4679,
  1193,
  3182,
  1243,
  4750,
  2658,
  1063,
  1028,
  4558,
  1372,
  1125,
  4650,
  2249,
  3294,
  2420],
 [670, 4990, 4571, 206, 4350, 4062, 4925, 1706, 2693, 658, 3637],
 [1350, 1648, 4258, 3657, 2354, 4856, 2658, 4578, 2693, 658, 3637],
 [4308, 3960, 4337, 929, 4444, 1034, 3575, 3227, 2658, 2170],
 [4100, 1455, 4293, 2229, 202, 2647, 4189, 623],
 [211, 346, 2590, 1568, 2706, 4987, 4568, 3307, 102, 4561, 3412],
 [881, 3788, 4377, 1034, 2658, 2354],
 [720, 3251, 1402, 3063, 2383, 765, 2595, 4287, 3249],
 [1697, 3095, 2921, 109, 4169, 1985, 3680, 2693, 658, 3637],
 [3832, 988, 4882, 4528, 4891, 2693, 658, 3637],
 [2582, 3319, 3441, 69, 2167, 2437, 4802, 1738, 1801, 1863],
 [3764, 827, 2706],
 [1733, 1089, 1744, 438, 2658, 1533, 264, 2420],
 [28

In [31]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ... 4786 2539 4738]
 [   0    0    0 ... 3878 4114 2420]
 [   0    0    0 ...  304 3803 1562]
 ...
 [   0    0    0 ... 2693  658 3637]
 [   0    0    0 ... 2693  658 3637]
 [   0    0    0 ... 1551  248 4515]]


In [32]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0, 1971,
       1692, 1392, 4940, 4377, 1106, 1260, 4786, 2539, 4738], dtype=int32)

In [33]:
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 20, 40)            200000    
                                                                 
 lstm (LSTM)                 (None, 100)               56400     
                                                                 
 dense (Dense)               (None, 1)                 101       
                                                                 
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [ ]:
#!pip install numpy==1.19.5

In [34]:
len(embedded_docs),y.shape

(13703, (13703,))

In [35]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [36]:
X_final.shape,y_final.shape

((13703, 20), (13703,))

In [37]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

# Model Training

In [38]:
### Finally Training
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
144/144 [==============================] - 8s 16ms/step - loss: 0.3826 - accuracy: 0.8230 - val_loss: 0.2034 - val_accuracy: 0.9120
Epoch 2/10
144/144 [==============================] - 2s 13ms/step - loss: 0.1425 - accuracy: 0.9460 - val_loss: 0.1863 - val_accuracy: 0.9233
Epoch 3/10
144/144 [==============================] - 2s 13ms/step - loss: 0.0918 - accuracy: 0.9678 - val_loss: 0.2286 - val_accuracy: 0.9224
Epoch 4/10
144/144 [==============================] - 2s 13ms/step - loss: 0.0642 - accuracy: 0.9787 - val_loss: 0.2333 - val_accuracy: 0.9169
Epoch 5/10
144/144 [==============================] - 2s 13ms/step - loss: 0.0468 - accuracy: 0.9843 - val_loss: 0.2787 - val_accuracy: 0.9215
Epoch 6/10
144/144 [==============================] - 2s 13ms/step - loss: 0.0311 - accuracy: 0.9901 - val_loss: 0.3723 - val_accuracy: 0.9120
Epoch 7/10
144/144 [==============================] - 2s 13ms/step - loss: 0.0193 - accuracy: 0.9936 - val_loss: 0.4540 - val_accuracy: 0.9166

# Adding Dropouts

In [ ]:
from tensorflow.keras.layers import Dropout
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

# Performance matrix and accuracy

In [39]:
y_pred=model.predict_classes(X_test)

AttributeError: ignored

In [40]:
from sklearn.metrics import confusion_matrix

In [41]:
confusion_matrix(y_test,y_pred)

NameError: ignored

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)